classDiagram
direction LR


class Usuario {
  +int IdUsuario
  +string Nombre
  +string Correo
  +string Telefono
  +string Rol
  +bool Activo
}
Usuario ..> auth.users : Vinculado
note for Usuario "Autenticación manejada por Supabase (auth.users)"



%% CATEGORIA Y PRODUCTO
class Categoria {
  +int IdCategoria
  +string Nombre
  +string Descripcion
  +bool Activo
}

class Producto {
  +int IdProducto
  +int IdCategoria_FK
  +string Nombre
  +string Marca
  +string Modelo
  +float Precio
  +int Stock
  +int GarantiaMeses
  +bool Activo
}

Categoria "1" --> "0..*" Producto : Clasifica


%% CARRITO
class Carrito {
  +int IdCarrito
  +int IdUsuario_FK
  +date FechaCreacion
}

class DetalleCarrito {
  +int IdDetalleCarrito
  +int IdCarrito_FK
  +int IdProducto_FK
  +int Cantidad
  +float Subtotal
}

Usuario "1" --> "0..1" Carrito : Tiene
Carrito "1" --> "1..*" DetalleCarrito : Contiene
Producto "1" --> "0..*" DetalleCarrito : Agregado


%% VENTA
class Venta {
  +int IdVenta
  +int IdUsuario_FK
  +date Fecha
  +float Total
  +string Estado
}

class DetalleVenta {
  +int IdDetalleVenta
  +int IdVenta_FK
  +int IdProducto_FK
  +int Cantidad
  +float PrecioUnitario
  +float Subtotal
}

Usuario "1" --> "0..*" Venta : Realiza
Venta "1" --> "1..*" DetalleVenta : Contiene
Producto "1" --> "0..*" DetalleVenta : Incluye